#连接mysql数据库
spring:
  datasource:
    url: jdbc:h2:mem:easy-code;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    schema: classpath:db/h2-schema.sql
    data: classpath:db/h2-data.sql
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    cn.edu.cqvie: info
    cn.edu.cqvie.ssm.dao: debug

server:
  port: 12345

pagehelper:
  helperDialect: h2
