#环境变量
spring:
  profiles:
    active: dev
  #数据源
  redis:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 16
      maximum-pool-size: 1200
      auto-commit: false
      connection-timeout: 30000
      connection-test-query: select 1

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
