spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:            # 没有可以不填
    lettuce:             # 连接池配置
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 10
    timeout: 1000
  cache: redis