server:
  port: 9001

eureka:
  client:
    serviceUrl:
      # 这里要注意是小驼峰如果填写为中划线, 会导致配置失效
      defaultZone: http://127.0.0.1:3000/eureka/
  instance:
    instance-id: ${spring.application.name}-01
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒


spring:
  application:
    name: service-payment

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'